version: "2"
run:
  timeout: 5m
  tests: false
output:
  formats:
    text:
      path: stdout
      colors: true
linters:
  exclusions:
    paths:
      - "zz_generated_*"
  disable:
    - errcheck
  enable:
    - revive # replacement for golint
    - dupl # check duplicated code
    - goconst # check strings that can turn into constants
    - goheader # Check license headers, only checks files in current year
    - gocyclo # check complexity
  settings:
    revive:
      rules:
        - name: dot-imports
          disabled: true
    goconst:
      min-occurrences: 9
    gocyclo:
      min-complexity: 20 # default is 30 which is too high
    goheader:
      template: |-
        Copyright © 2022 - {{ year }} SUSE LLC
        
        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at
        
            http://www.apache.org/licenses/LICENSE-2.0
        
        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1005"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-QF1004"
        - "-QF1007"
        - "-QF1008"
formatters:
  enable:
    - goimports
    - gofmt
