apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ .Release.Name }}'
  namespace: fleet-default
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Release.Name }}'
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventoryselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventoryselectors/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineregistrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedoschangelogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedoschangelogs/finalizers
  verbs:
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedoschangelogs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedosimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedosimages/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedosversionchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedosversionchannels/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedosversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - managedosversions/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - seedimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - seedimages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundles
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - ipaddressclaims
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - ipaddresseclaims
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - ipaddresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Release.Name }}'
  namespace: fleet-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ .Release.Name }}'
  namespace: fleet-default
subjects:
- kind: ServiceAccount
  name: '{{ .Release.Name }}'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ .Release.Name }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Release.Name }}'
subjects:
- kind: ServiceAccount
  name: '{{ .Release.Name }}'
  namespace: '{{ .Release.Namespace }}'
