# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/opensuse15"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.check_guest_additions = false
    vb.memory = ENV['VAGRANT_MEMORY'] || "4096"
    vb.cpus = ENV['VAGRANT_CPU'] || "2"
  end

  config.vm.provision "shell", path: "./assets/script.sh", run: "once"
  config.vm.provision "file",  source: "./assets/external_charts.yaml", destination: "/tmp/charts.yaml", run: "once"
  config.vm.provision "file",  source: "./assets/setting.yaml", destination: "/tmp/setting.yaml", run: "once"
  config.vm.provision "shell", inline: "until k3s --version; do sleep 1; done", run: "once"
  config.vm.provision "shell", inline: "until k3s kubectl apply -f /tmp/charts.yaml; do sleep 1; done", run: "once"
  config.vm.provision "shell", inline: "until k3s kubectl wait --for=condition=Ready pod -l app=rancher -n cattle-system; do sleep 1; done"
  config.vm.provision "shell", inline: "until k3s kubectl get setting; do sleep 1;done", run: "once"
  config.vm.provision "shell", inline: "until k3s kubectl apply -f /tmp/setting.yaml; do sleep 1; done", run: "once"
end
