# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/elemental.cattle.io_machineinventories.yaml
- bases/elemental.cattle.io_machineinventoryselectors.yaml
- bases/elemental.cattle.io_machineinventoryselectortemplates.yaml
- bases/elemental.cattle.io_machineregistrations.yaml
- bases/elemental.cattle.io_metadata.yaml
- bases/elemental.cattle.io_managedosversionchannels.yaml
- bases/elemental.cattle.io_managedoschangelogs.yaml
- bases/elemental.cattle.io_managedosimages.yaml
- bases/elemental.cattle.io_managedosversions.yaml
- bases/elemental.cattle.io_seedimages.yaml
# +kubebuilder:scaffold:crdkustomizeresource

commonLabels:
  release-name: '{{ .Release.Name }}'
  cluster.x-k8s.io/provider: infrastructure-elemental
  cluster.x-k8s.io/v1beta1: v1beta1

commonAnnotations:
  app.kubernetes.io/instance: '{{ .Release.Name }}'
  app.kubernetes.io/version: '{{ .Chart.Version }}'
  app.kubernetes.io/part-of: 'Elemental Operator' 
